## ========================================================================= ##
# Title:    Analysis and Visualization of Student Interaction and Pathways 
#           through Learning Objectives associated with an edX Course
# Project:  edX learner objective analysis
# 
#     Copyright 2019-2020 Michael Ginda
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description: This visual analytics script analyzes students interactions and
#              pathways through edX course modules, captured via edX event logs, 
#              in the context of learning objectives implemented and aligned to  
#              course content by instructional designers. The script processes 
#              analyzes data for cohorts of students enrolled in the edX course
#              by translating their interactions with content to interactions 
#              with groups of learning objectives for a course.
#
#              After processing the event logs, the script calculates the number 
#              interaction events and dwell times associated with learning 
#              objectives generated by a cohort of students enrolled in
#              an edX course, and generates a transition network between 
#              learning objectives based on the pathways taken by students in
#              the cohort. 
#
#              Dwell time associated with each learning objective is visualized
#              using as an area chart for the length of the course; while the
#              cohort's learning objective transition matrix is visualized using
#              a heatmap visualization.
#
#              This script relies on data processing results generated by the
#              edX Learner and Course Analytics and Visualization Pipeline, 
#              which is described in the publication:
#               - Ginda, M., Richey, M. C., Cousino, M., & Börner, K. (2019). 
#                 Visualizing learner engagement, performance, and trajectories 
#                 to evaluate and optimize online course design. 
#                 PloS one, 14(5), e0215964.
#               - https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0215964 
#              and documented in a GitHub repository:
#               - https://github.com/cns-iu/edx-learnertrajectorynetpipeline
#
# File input stack: 
#            1) A processed edX Course structure and content module list coded
#               with learning objectives associated with the edX course, using 
#               a modified version of the edX course structure generated by:
#               - {org}+{course}+{term}-module-lookup.csv;
#               - extracted by script, edX-0-courseStructureMeta.R;
#            2) A list of student userIDs from an edX course:
#               - {org}-{course}-{term}-auth_user-students.csv;
#               - extracted by script, edX-1-studentUserList.R;
#            3) A "studentevents_processed" directory containing one or more 
#               student CSV event log file(s):
#               - {userID}.csv;
#               - extracted by scripts, edX-3-eventLogExtractor.R and 
#                 edX-4-eventLogFormatter.R.
#
# Output files:                        
#            1) A set of processed data tables of event action logs 
#               for each student and descriptive statistics:
#               - interact.csv;
#               - interact-stat.csv
#            2) Edge lists of students' transitions through course's learning
#               objectives
#               - edges.csv;
#               - edges-weighted.csv
#            3) A visualization with learning object dwell time area graphs, and
#               a heatmap of students transitions between learning objectives:
#               - panel-area+heatmap-divg-logNormed-labsAvgTrans.png;
#
# Package dependencies: tcltk, tidyr, plyr, dplyr, reshape2,igraph, ggplot2
#                       viridris, and gridExtra
#
# Change log:
# 12.2019 - Initial code creating learning objective transition network with  
#           dwell time analysis as a network heatmap visualization.
# 07.2020 - Preparing code for publication and re-use
#
## ========================================================================== ##

#### Environmental Setup ####
#rm(list=ls()) 

# Load required packages
library(tcltk2)     # for OS independent GUI file and folder selection
library(tidyr)      # for data preparation
library(plyr)       # for data aggregations
library(dplyr)      # for filtering
library(reshape2)   # for data reshaping
library(igraph)     # for creating an adjacency matrix
library(ggplot2)    # for visualization
library(viridis)    # for color scales
library(gridExtra)  # for arranging figures

#### Paths #### 
#Checks if a user has previously assign a path with a prior script 
#If false, lets user assign path to previous processing output files of an
#edX course using the a previous processing scripts from this pipeline.
if(exists("path_output")==FALSE){
  path_output = tclvalue(tkchooseDirectory())
}

#### Load Data ####
# Course Module Learning Objective Analysis Results
lo <- read.csv(file=list.files(full.names = TRUE, recursive = FALSE, 
                                 path = paste0(path_output,"/learningObjectives/"),
                                 pattern = "module-learningObjectives.csv$"), header=T)

# Create paths to student logs data
# Load list of users to create list of log file paths
users <- read.csv(list.files(full.names = TRUE, recursive = FALSE, 
                                 path = paste0(path_output,"/state/"),
                                 pattern = "auth_user-students-ids.csv$"),header=T)
names(users) <- "id"

# Create list of filepaths to processed student event logs
filePaths <- paste0(path_output,"/results/studentevents_processed/",users$id,".csv")

#### Data Processing ####
# Save the time (to compute elapsed time of script)
start <-  proc.time() 

# Preparing Learning Objectives Data
# Reshape Learning Objective matrix to a list, NAs removed from data set (hidden modules or instructions for course)
lo <- lo %>% reshape2::melt(id.vars=c(1:13), variable.name="learningObjective",na.rm=T)
# Updates objective factors
lo$learningObjective <-  gsub("\\.", " ",lo$learningObjective)

# Learning Objective identifier data frame
lo_id <- as.data.frame(unique(lo$learningObjective))
names(lo_id) <- "learningObjective"

# Learning Objectives to Sequential Modules
# Subset to only values 1, indicating a learning objective was observed, and tree levels of 2 (sequential modules), 
# then re-factor identifiers
lo_s <- lo[lo$value==1 & lo$treelevel==2,c("mod_id","mod_type","learningObjective")] %>% 
  mutate(mod_id = factor(mod_id)) %>% mutate(mod_type = factor(mod_type))

# Learning Objectives to Content Modules
# Subset to only values 1, indicating a learning objective was observed, and tree levels of 4 (content modules), 
# then re-factor identifiers
lo_c <- lo[lo$value==1 & lo$treelevel==4,c("mod_id","mod_type","seqModPar","learningObjective")] %>% 
        mutate(mod_id = factor(mod_id)) %>% mutate(mod_type = factor(mod_type))

# Learning Objective Activity Calculations data frame
act  <- data.frame(learningObjective=as.character(),             # Learning Objective
                   events=as.numeric(),                          # Event Count
                   dwell=as.numeric(),                           # Dwell Time (Min)
                   created=as.POSIXct(as.character()),           # First Event Log Created
                   modified=as.POSIXct(as.character()),          # Last Modification to Event Log
                   user_id=as.integer(),                         # Student Identifier
                   stringsAsFactors=FALSE)

# Learning Objective Network Edge List Setting
# Self loops are kept in this network because they are relevant sequences where students work
# on the same objective for a period of time.
selfLoopKeep <- T 

# Learning Objective Edge List for Adjacency Network
edges <- data.frame(user_id=as.integer(),                        # Student Identifier
                    from=as.character(),                         # Learning Objective - Source
                    f.mod_id=as.character(),                     # Content Module - Source
                    to=as.character(),                           # Learning Objective - Target 
                    t.mod_id=as.character(),                     # Content Module - Target
                    time=as.POSIXct(as.character()),             # Date Time Stamp
                    stringsAsFactors=FALSE)

# Analyzing Student Logs length(filePaths)
# Loop individual student logs to create an edge list of transitions between learning objectives
for(i in 1:length(filePaths)){
  message("Processing log file ", i, " of ", length(filePaths))
  print(proc.time() - start)
  ## Load data set
  data <- read.csv(filePaths[i])[,c("course_id","user_id","mod_hex_id","time","period",
                                     "attempts","grade","max_grade","success")]
  # Renames field to join with Learning Objectives 
  names(data)[3] <- "mod_id"
 
  #Updates Time field to R compliant format
  data$time  <- as.POSIXct(data$time,origin="1970-01-01") 

  # Left join learning objectives for content modules (lo_c) to student log (data)
  data <- join(as.data.frame(data), as.data.frame(lo_c[,c("mod_id","learningObjective")]), by="mod_id")
  
  # Remove all events that are not associated with an objective
  data <- data[!is.na(data$learningObjective),]

  # Learning Objective Dwell Time and Event Count Calculations
  tmp <- data %>% 
         ddply(.,~learningObjective,summarise,
                  events = length(period),             # Total number of events
                  dwell = sum(period),                 # Total dwell time
                  create = min(time),                  # Date created
                  modified = max(time),                # Date modified
                  user_id = unique(user_id)) %>%       # Students id
         replace_na(list(dwell=0, events=0, user_id=unique(data$user_id))) 

  # Learning Objecitve Problem Attempts and Problem Dwell Time
  tmp <- data %>% 
         filter(attempts == !is.na(attempts)) %>%      # Filter to all problem modules
         ddply(.,~learningObjective,summarise,         # Calculates attempts at a problem mod
               attempts = length(attempts),            # Problem attempts period field in logs
               prb_dwell = sum(period),                # Problem dwell time using period field in logs
               user_id = unique(user_id)) %>%          # Students id
         join(tmp,.,by=c("learningObjective","user_id")) %>%
         replace_na(list(attempts=0, prb_dwell=0)) %>%
         select(1:5,7:8,6)
  
  #Add rows to student data calculations for activity in course
  act  <- rbind(act,tmp)
  
  #Adjacency Edge List
  if(nrow(data)>1){
    ## Edge List Created
    tmp <- data[,c("user_id","learningObjective","mod_id","time","period")] 
    #Creates transitions in targets in edge file
    tmp <- cbind(tmp[1:(nrow(tmp)-1),c(1:3,5)],tmp[2:nrow(tmp),c(2:4)])
    #Renames fields
    names(tmp) <- c("user_id","from","f.mod_id","period","to","t.mod_id","time")
    tmp <- tmp[,c(1:3,5:7,4)]
    #Adds self loops flag, and reorganizes the columns
    tmp$sl <- 0
    if(selfLoopKeep==T){
      if(length(tmp[tmp$to==tmp$from,]$sl)>=1){
        tmp[tmp$to==tmp$from,]$sl <- 1
      }
    } else {
      tmp <- tmp[tmp$to==tmp$from,]
    }
  }
  edges <- rbind(edges,tmp)
}

#Clean up environment
rm(i,tmp,data,selfLoopKeep)

## Dwell Time and Edge Data Analysis - Cohort Analysis ####
# Create data.frames
edges_s <- act_s <- data.frame()

# LO Activity Descriptive Statistics - Events and Dwell Time
for(i in 1:nrow(lo_id)){
  data <- act[act$learningObjective==lo_id[i,1],]
  students <- length(unique(data$user_id))
  events <- sum(data$events)
  avgEvents <- mean(data$events)
  varEvents <- var(data$events)
  sdEvents <- sd(data$events)
  seEvents <- sd(data$events)/length(unique(data$user_id))
  mdEvents <- median(data$events)
  dwell <- sum(data$dwell)
  avgDwell <- mean(data$dwell)
  varDwell <- var(data$dwell)
  sdDwell <- sd(data$dwell)
  seDwell <- sd(data$dwell)/length(unique(data$user_id))
  mdDwell <- median(data$dwell)
  data <- cbind(students,events,avgEvents,varEvents,sdEvents,seEvents,mdEvents,dwell,avgDwell,varDwell,sdDwell,seDwell,mdDwell)
  act_s <- rbind(act_s,data)
}
rm(i,students,events,dwell,avgEvents,varEvents,sdEvents,seEvents,mdEvents,avgDwell,varDwell,sdDwell,seDwell,mdDwell)
act_s <- cbind(lo_id,act_s)

# LO Transition Network Descriptives Statistics
edges_s <- ddply(edges, ~ from + to, summarise,
                weight = length(user_id),
                weight_l = log(length(user_id)),
                weight_avg = length(user_id)/length(unique(user_id)),
                uniStu = length(unique(user_id)))
edges_s$from <- as.character(edges_s$from)
edges_s$to <- as.character(edges_s$to)
edges_s$weight_l <- as.numeric(edges_s$weight_l)
edges_s$weight_avg <- as.numeric(edges_s$weight_avg)
edges_s$uniStu <- as.numeric(edges_s$uniStu)

## Temporal Analysis - Daily Student Actitity - Events and Dwell Time ####
eds <- edges[,c(1:2,6)] %>% group_by(date = cut(time,"day"))

# Pass new df to find distinct list of students active on a day
eds <- eds[,c(1,2,4)] %>% distinct() %>% 
  melt(id=c("date","from"), value.name = "user_id") %>% 
  ddply(date~from,summarise,
        students = length(unique(user_id))) #%>%

# Daily Events Calculations
ede <- edges %>% group_by(date = cut(time,"day")) %>% 
  ddply(date~from,summarise,
        events=length(period))

# Combine events to with daily measure data set
eds$events <- ede$events
eds$avgEvents <- eds$events/eds$students
rm(ede)

# Daily Dwell Time
edt <- edges %>% group_by(date = cut(time,"day")) %>% 
  ddply(date~from,summarise,
        dwellTime=sum(period))

# Combine dwell time with daily measure data set
eds$dwellTime <- edt$dwellTime
eds$dwellTime <- eds$dwellTime/60
eds$avgDwellTime <- eds$dwellTime/eds$students
rm(edt)
# Update dates to as.Date()
eds$date<- as.Date(eds$date)

#Update learning objective factors
names(eds)[2] <- "learningObjective"
eds$learningObjective <- factor(eds$learningObjective, levels=c("LO 9","LO 8","LO 7","LO 6","LO 4","LO 3","LO 2","LO 1"))

## Analysis Results Output ####
write.csv(act_s, file=paste0(path_output,"/results/analysis/dwell-stats.csv"),row.names = F)
write.csv(act, file=paste0(path_output,"/results/analysis/dwell.csv"),row.names = F)
write.csv(edges[,c(1,2,4,6)], file=paste0(path_output,"/results/analysis/edges.csv"),row.names = F)
write.csv(edges_s,file=paste0(path_output,"/results/analysis/edge-weighted.csv"), row.names = F)

#### Visualizations ####
## Panel A: Vlines data set for weekly breaks in course timeline ####
wk <- as.data.frame(levels(cut(edges$time,"week")))
names(wk) = "week"
wk$week <- as.Date(wk$week)

# Panel A: Labels with sum total and average dwell time for course ####
a_textLabs <- data.frame(
  x=max(wk[8,]-3.5),
  learningObjective = act_s$learningObjective,
  label = paste0("Total Dwell Time: ", round(act_s$dwell/60,0)," h.",
                 "\nMean Dwell Time: ", round(act_s$avgDwell/60,2)," h.")
)
# Align factors with eds$learningObjectives
a_textLabs$learningObjective <- factor(a_textLabs$learningObjective, levels=c("LO 9","LO 8","LO 7","LO 6","LO 4","LO 3","LO 2","LO 1"))

# Panel A: Timeline of Learning Objective Dwell Time by Day of the Week ####
a <- ggplot(eds, aes(x=date, y=dwellTime, fill=learningObjective)) + 
            geom_vline(aes(xintercept=week),wk,
                       linetype=3, size=.25,
                       colour="grey80") +
            geom_text(aes(x=x, y=700, label=label), a_textLabs,
                       hjust=.1,
                       size=2.5 , colour="grey40") +
            geom_area() + 
            scale_fill_viridis(option="magma", discrete = T, begin = 0.4, end = .4) +
            scale_x_date(breaks = wk$week, date_labels ="%b %d") +
            facet_wrap(~learningObjective, nrow = length(levels(eds$learningObjective))) +
            labs(tag = "A",
                 x=paste0("Course Timeline"),
                 y=paste0("Total Dwell Time (h)")) +
            theme(axis.title.x = element_text(hjust=1, colour="grey20",
                                              margin=unit(c(3,0,0,0),"mm")),
                  axis.ticks.x.bottom = element_line(colour="grey60", linetype = "solid"),
                  axis.text.x=element_text(size=7),
                  axis.line.x = element_blank(),
                  axis.title.y = element_text(hjust=.96, colour="grey20",
                                              margin=unit(c(0,3,0,0),"mm")),
                  axis.text.y=element_text(size=7),
                  axis.ticks.y = element_line(colour="grey60", linetype = "solid"),
                  panel.background = element_rect(fill = "grey98"),
                  panel.grid.major.x = element_blank(),
                  panel.grid.minor.x = element_blank(),
                  panel.grid.major.y = element_blank(),
                  panel.grid.minor.y = element_blank(),
                  strip.background = element_blank(), 
                  strip.text.x = element_blank(),
                  legend.position = "none")

## Panel A & B: Mid-panel labels ####
g.mid <- ggplot(act_s,aes(x=1,y=learningObjective))+
                geom_text(aes(label=learningObjective), size=3 , color="grey20")+
                labs(y=NULL)+
                scale_x_continuous(expand=c(0,0),limits=c(0.93,1.066))+
                theme(axis.title=element_blank(),
                      panel.grid=element_blank(),
                      axis.text.y=element_blank(),
                      axis.ticks.y=element_blank(),
                      panel.background=element_blank(),
                      axis.text.x=element_text(color=NA),
                      axis.ticks.x=element_line(color=NA),
                      plot.margin = unit(c(6,0,6,5), "mm"))

## Panel B: Heatmap of Adjacency Matice ####
b <- ggplot(edges_s,aes(x=to,y=from)) + 
            geom_tile(aes(fill=weight_l)) +
            geom_text(aes(label = round(weight_avg, 1)),
                      #label = round(uniStu/max(uniStu)*100, 2)),
                      colour="grey10") +
            labs(tag = "B",
                 x=paste0("Learning Objectives - Targets"),
                 #caption = "Cell labels show the average number of transitions between\nlearning objectives made by students.",
                 #caption = "Labels show the percentage of students making a transition in the heatmap.",
                 fill="Weighted\nNode\nAdjacency\n(Log Scaled)") +
            scale_fill_gradientn(colours=magma(100, alpha = .8, begin = .3, end = 1, direction = 1)) +
            guides(fill = guide_colorbar(label.theme = element_text(colour="grey30"),
                                         frame.colour = "grey60")
            ) +
            theme(axis.title.x = element_text(hjust=.065, colour="grey20",
                                              margin=unit(c(3,0,0,0),"mm")),
                  axis.ticks.x.bottom = element_line(colour="grey60", linetype = "solid"),
                  axis.line.x = element_blank(),
                  axis.title.y = element_blank(),
                  axis.text.y = element_blank(),
                  axis.ticks.y = element_blank(),
                  panel.background = element_rect(fill = "white"),
                  panel.grid.major.x = element_blank(),
                  panel.grid.major.y = element_blank()
            )

## Final Grid Arrangement with Area Graphs of Student Dwell Time and Learning Objective Transition Heatmap####
# Learning Objective Adjacency Network Heatmap with Percent of Students Making Transtion Labeled
# AB - Area + overall Heatmap
png(filename=paste0(path_output,"/results/visualization/panel-area+heatmap-divg-logNormed-labsAvgTrans.png"),
    width = 10, height = 4.55, units = "in", pointsize = 10, res=300,
    type="cairo", bg = "white")
grid.arrange(a,g.mid,b,ncol=3,widths=c(3.75/10,.5/10,4.75/10))
dev.off()

#### Finishing Details ####
#Indicate completion
message("\n**** Complete! ****\n")
## Script processing time feedback
#print the amount of time the script required
cat("\n\n\nComplete script processing time details (in sec):\n")
print((proc.time()[3] - start[3])/60)
## Clear environment variables
#rm(list=ls())